# Generated by Django 5.2.13 on 2026-05-05 14:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pcs', 'Pcs'), ('kg', 'Kg'), ('gram', 'Gram'), ('liter', 'Liter'), ('meter', 'Meter'), ('box', 'Box'), ('lusin', 'Lusin'), ('karton', 'Karton')], default='pcs', max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('stock_min', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.tenant')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
